name: project
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # svgファイルを追加したい(nullsafetyじゃない)
  flutter_svg: ^0.19.3
  # firebase連携(nullsafetyじゃない)
  firebase_core: "0.7.0"
  cloud_firestore: "^0.16.0"
  # 外部リンクで開くために追加
  url_launcher: ^5.7.10
  # アプリ共有するために追加
  share: ^0.6.5+4
  # ローカルデータを保存するために追加
  shared_preferences: ^0.5.12+4
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  # 背景素材置き場 
  - movies/
  - images/
  # svg素材置き場
  - assets/